/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : adc_pal1.c
**     Project     : FUXIN_S32K148
**     Processor   : S32K148_176
**     Component   : adc_pal
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2022-03-17, 14:54, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file adc_pal1.c
** @version 01.00
*/         
/*!
**  @addtogroup adc_pal1_module adc_pal1 module documentation
**  @{
*/         

/* MODULE adc_pal1. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files, with the same initialized values.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.9, Could define variable at block scope.
 * The external variables will be used in other source files, with the same initialized values.
 */ 

#include <stddef.h>
#include "adc_pal1.h"

/*! @brief PAL instance information */

const adc_instance_t adc_pal1_instance = { ADC_INST_TYPE_ADC_S32K1xx, 0u };

/*! @brief Configuration 0 declaration */

static extension_adc_s32k1xx_t adc_pal1_Extension0 = {
    .clockDivide              = ADC_CLK_DIVIDE_1,
    .resolution               = ADC_RESOLUTION_8BIT,
    .inputClock               = ADC_CLK_ALT_1,
    .voltageRef               = ADC_VOLTAGEREF_VREF,
    .supplyMonitoringEnable   = true,
    .pdbPrescaler             = PDB_CLK_PREDIV_BY_1
};

const adc_config_t adc_pal1_InitConfig0 = {
    .sampleTicks        = 150,
    .numGroups          = 1,
    .groupConfigArray   = adc_pal1_GroupArray0,
    .extension          = &adc_pal1_Extension0
};

const adc_group_config_t adc_pal1_GroupArray0[1u] = {
    /* Conversion group 0 */
    {
        adc_pal1_ChansArray00,     /* inputChannelArray */
        adc_pal1_Results00,        /* resultBuffer */
        4,     /* numChannels */
        1,     /* numSetsResultBuffer */
        false,        /* hwTriggerSupport */
        TRGMUX_TRIG_SOURCE_DISABLED,     /* triggerSource */
        ADC_DELAY_TYPE_NO_DELAY,      /* delayType */
        NULL,       /* delayArray */
        false,     /* continuousConvEn */
        adc_pal1_callback,       /* callback */
        NULL        /* callbackUserData */
    },
};

adc_input_chan_t adc_pal1_ChansArray00[4u] = {
    ADC_INPUTCHAN_EXT28,
    ADC_INPUTCHAN_EXT28,
    ADC_INPUTCHAN_EXT28,
    ADC_INPUTCHAN_EXT28,
};
uint16_t adc_pal1_Results00[(4u) * (1u)];


/* END adc_pal1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
